### ISSUE TITLE
Can't set an expiration time longer then 7200 seconds.

### ISSUE THREAD

**Issue by AionDev** [bryanjos/joken#180] opened 2018-02-14 18:33 UTC
From what i understand, this function [`with_exp/2`](https://hexdocs.pm/joken/1.5.0/Joken.html#with_exp/2) is supposed to allow me to set a custom expiration time. Using [`with_exp/1`](https://hexdocs.pm/joken/1.5.0/Joken.html#with_exp/1) gives 2 hours expiration time by default. 

I want my token to be valid 1 year.

```
access_token =
  Joken.token()
  |> Joken.with_sub("123")
  |> Joken.with_exp(31_537_000)   # aprox nr of seconds in a year
  |> Joken.with_iat()
  |> IO.inspect()                 # see the inspect below
  |> Joken.sign(Joken.rs256(private_key))
  |> Joken.get_compact()
```
I get this token: 
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MTg2Mzk1ODcsImlhdCI6MTUxODYzMjM4NywibmJmIjoxNTE4NjMyMzg2LCJzdWIiOiIxMjMifQ.QCEpil4hEVH18gaybOfKnH6KzgW-D_AADgZbtgO_HUXH5UkFewC7HxBMh3X-b9Kw0T8drtVemDWRk_MvSLHf-Wflm0v7yXym1nRk73gDnptT9Ot5-FFm25jQOA4CdVA8d0tvKbSJ0uyqlACKxzXn0fy9hObp8khF8xIy0N58dGHPQSuj6sUkAScGEI3u-zSLoG4m9GFGubwYd27CIR3iajS3sKr-eBX36O1hvkuJ7XEUPCJkxWL0LC7G35shb3JTaJvcNjZMxlSvtfDo3iMaAEtx_qTENQUGO3T_Di97Z20Xwijg6Fb7hz7bJftdLYB4D0vz552px1LHnRhDZRCsng
```
By verifing with [jwt.io](https://jwt.io/) the token payload is this:
```
{
  "exp": 1518639587,
  "iat": 1518632387,
  "nbf": 1518632386,
  "sub": "123"
}
```
`exp - iat = 7200` **=> 2 hours instead of 1 year.**
This makes me think that my custom value is discarded and this function: [`with_exp/2`](https://hexdocs.pm/joken/1.5.0/Joken.html#with_exp/2) doesn't work as expected. I think that [`with_exp/1`](https://hexdocs.pm/joken/1.5.0/Joken.html#with_exp/1) is being used instead.

This is a log of the `IO.inspect`:
```
%Joken.Token{
  claims: %{"exp" => 31537000, "sub" => "123"},              # here is just fine - 1 year.
  claims_generation: %{
    "exp" => #Function<3.121810920/0 in Joken.with_exp/1>,   # im guessing this is the problem - should be with_exp/2 not /1
    "iat" => #Function<4.121810920/0 in Joken.with_iat/1>,
    "nbf" => #Function<5.121810920/0 in Joken.with_nbf/1>
  },
  error: nil,
  errors: [],
  header: %{},
  json_module: Poison,
  signer: nil,
  token: nil,
  validations: %{
    "exp" => {#Function<0.121810920/1 in Joken.token/0>, nil},
    "iat" => {#Function<1.121810920/1 in Joken.token/0>, nil},
    "nbf" => {#Function<2.121810920/1 in Joken.token/0>, nil}
  }
}
```
Is this a bug or i'm misunderstanding something 🙂 ?

**Comment by victorolinasc** [comment] 2018-02-14 19:46
This is a bad API decision on our part and one of the reasons we are preparing a v2 of Joken.

What is happening here is that exp is a a dynamic claim. That means: its value should be generated when we sign the token. The issue is that with current API we have both `claims_generation` and `claims`. So, when you set exp to a static value it gets overwritten by the dynamic value.

What you *can* do now is to write it like this:

```elixir
access_token =
  Joken.token()
  |> Joken.with_sub("123")
  # Will generate a 1 year valid "exp" claim
  |> Joken.with_claim_generator("exp", fn -> Joken.current_time() + <<one year>> end) 
  |> Joken.with_iat()
  |> IO.inspect()                 # see the inspect below
  |> Joken.sign(Joken.rs256(private_key))
  |> Joken.get_compact()
```

The default exp is generated with the claim_generator so its dynamic and has precedence over static claims. So, its a bug in the design which is a bad bug. 

The reason we haven't touched the `with_exp/2` calls is because of backwards compatibility. v2 will fix that and should be out soon.

**Comment by victorolinasc** [comment] 2018-02-15 00:24
Can we close this one for now? I know it is not the best API currently, but it is kinda of "solved" I guess.

**Comment by AionDev** [comment] 2018-02-15 19:23
@victorolinasc yes go ahead. The provided solution worked just fine. Thanks 😄

**Closed** 2018-02-16 19:48 UTC
